In [1]:
import numpy

In [8]:
G = 0.5*numpy.matrix([[87.8, -86.4],
                      [108.2, -109.6]])
Gd = numpy.matrix([[7.88, 8.81],[11.72, 11.19]])

In [10]:
sigmas = numpy.linalg.svd(G)[1]
sigmas

array([98.60434061,  0.69570974])

In [29]:
Uh = numpy.linalg.svd(G)[0]
Uh.getH()

matrix([[-0.62460327, -0.78094223],
        [-0.78094223,  0.62460327]])

In [30]:
Uh.getH()*Gd

matrix([[-14.07451662, -14.24149828],
        [  1.16652554,   0.10920954]])

In [25]:
numpy.linalg.inv(G)*Gd

matrix([[-1.08571429, -0.0090379 ],
        [-1.28571429, -0.21311953]])